const result_api = {
  message: "",
  total_values: 1,
  values: [
    {
      additional_data: { dob: "2024-03-08", phone_number: "083873216202" },
      card: {
        card_id: "0838732162",
        end: 1711904340000,
        license_plate: "B4412KDN",
        membership_id: "a5e0b7ea-xxx",
        paid_date: "",
        payment_method: "",
        product_detail: {
          code: "CP-011b2f",
          created_at: "2024-03-08 06:45:25",
          description: "",
          extend_price: 100000,
          id: "1b2f4a8e-xxx",
          spot_id: "61c22d4f-xxx",
          status: true,
          type: "CORPORATE",
          updated_at: "2024-03-08 06:45:25",
          values: 1,
        },
        product_id: "1b2f4a8e-xxx",
        reference: "",
        rf_id: "0838732162",
        second_license_plate: "",
        start: 1709226000000,
      },
      card_id: "0838732162",
      company_id: "68e7004b-xxx",
      corporate_id: "60376185-xxx",
      created_at: "2024-03-08 09:12:20",
      current_holder: "",
      deleted_at: "",
      email: "",
      employee_phone: "",
      expired_card: {},
      id: "aec274ec-xxx",
      identification_number: "",
      mgmt_user_delete: {},
      mgmt_user_detail: {
        corporate_detail: {},
        email: "iqbal@soulparking.co.id",
        id: "7d60974d-xxx",
        name: "Ikbal maulana",
        phone: "085894525693",
        profile_picture: "https://url.image/mgmt/user/4d46e749-xxx.png",
        profile_picture_path: "mgmt/user/4d46e749-xxx.png",
        type: "S",
        username: "iqbal@soulparking.co.id",
      },
      mgmt_user_id: "7d60974d-xxx",
      motorcycle: [],
      name: "Ikbal maulana",
      officer_detail: {},
      officer_id: "7d60974d-xxx",
      owner_id: "",
      rf_id: "0838732162",
      spot_id: "61c22d4f-xxx",
      status: true,
    },
  ],
};

const result_api_motorcyle = {
  message: "",
  total_values: 1,
  values: [
    {
      additional_data: { dob: "2024-03-09", phone_number: "1212321312" },
      card: {},
      card_id: "",
      company_id: "ef61e60a-xxx",
      corporate_id: "9c3d5756-xxx",
      created_at: "2024-03-19 06:34:24",
      current_holder: "",
      deleted_at: "",
      email: "",
      employee_phone: "",
      expired_card: {},
      id: "707cd108-xxx",
      identification_number: "",
      mgmt_user_delete: {},
      mgmt_user_detail: {
        corporate_detail: {},
        email: "iqbal@soulparking.co.id",
        id: "7d60974d-xxx",
        name: "Ikbal maulana",
        phone: "085894525693",
        profile_picture: "https://via.place.hold/mgmt/user/4d46e749-xxx.png",
        profile_picture_path: "mgmt/user/4d46e749-xxx.png",
        type: "S",
        username: "iqbal@soulparking.co.id",
      },
      mgmt_user_id: "7d60974d-xxx",
      motorcycle: [
        {
          end: 1711990740000,
          license_plate: "B1010SPN",
          membership_id: "1701c8e7-xxxx",
          paid_date: "",
          payment_method: "",
          product_detail: {
            availability: 0,
            code: "PC015540",
            created_at: "2024-03-19 06:33:17",
            daily_price: 0,
            deadline: 1,
            description: "",
            extend_price: 0,
            id: "5540648e-xxx",
            is_complimentary: "NO",
            limit: 0,
            max_change: 0,
            name: "PRODUK CORPORATE",
            overstay_affected: "NO",
            period: "month",
            price: 300000,
            price_lp_change: 0,
            repeated_price: true,
            show_on_cashier: "NO",
            show_on_customer: "NO",
            spot_detail: {},
            spot_id: "5b03df07-d7xx",
            start: "FIRST_DAY_OF_MONTH",
            status: true,
            type: "CORPORATE",
            updated_at: "2024-03-19 06:33:17",
            values: 1,
            vehicle_code: "MT1",
            vehicle_detail: {
              alias: "alias jenis kendaraan MT1",
              code: "MT1",
              data_change_price: "5000",
              lost_card_price: "50000",
              name: "Motor Kecil",
              spot_id: "5b03df07-d7xx",
            },
          },
          product_id: "5540648e-xxx",
          reference: "",
          second_license_plate: "",
          start: 1709226000000,
        },
      ],
      name: "company 001",
      officer_detail: {},
      officer_id: "7d60974d-xxx",
      owner_id: "",
      rf_id: "",
      spot_id: "5b03df07-d7xx",
      status: true,
    },
  ],
};

export { result_api, result_api_motorcyle };
